### ISSUE TITLE
[1.12.2] [FTB Presents Stoneblock 2] java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by droobey** [SleepyTrousers/EnderCore#107]
Crash when loading FTB Presents Stoneblock 2 (MC 1.12.2) during startup

Game successfully started next launch. Reported as the game told me too (VanilaFix)

```
java.lang.NoClassDefFoundError: com/enderio/core/common/transform/EnderCorePlugin
    at com.enderio.core.common.mixin.SimpleMixinLoader.loadMixinSources(SimpleMixinLoader.java:8)
    at com.enderio.core.EnderCore.<init>(EnderCore.java:86)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
```

Full log https://paste.dimdev.org/kabiruxasi.mccrash

**Comment by tyler489** [comment]
Downgrade Endercore

**Comment by HenryLoenwind** [comment]
Please have a look in the actual log (not the crash report) if Forge logs an error about embedded libraries. Or post the log.

**Comment by PanSzelescik** [comment]
I have the same problem:
[latest.log](https://github.com/SleepyTrousers/EnderCore/files/3556109/latest.log)
[crash-2019-08-29_16.44.44-client.txt](https://github.com/SleepyTrousers/EnderCore/files/3556110/crash-2019-08-29_16.44.44-client.txt)

**Comment by HenryLoenwind** [comment]
```
[16:44:22] [main/WARN]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[16:44:22] [main/WARN]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
```

You are not using an official Forge release, are you?

**Comment by PanSzelescik** [comment]
I'm using Twitch Launcher which starts Mojang Launcher

**Comment by mahtaran** [comment]
Same problem for me when trying to depend on the mod in a developer environment:
[debug.log](https://github.com/SleepyTrousers/EnderCore/files/3562630/debug.log)

**Comment by HenryLoenwind** [comment]
Mahtaran, you are running a dev env. Forge does not automatically extract embedded jars from dependencies on the classpath (complain to them if you want), so you need to extract those and put them into your run/mods folder manually.

**Comment by mahtaran** [comment]
Oh wow, that is dumb. Seems to work now. Thanks!

**Comment by PanSzelescik** [comment]
With Forge 2838 on Twitch Launcher and Ender IO 5.1.51 works very well

**Comment by theoparis** [comment]
> Oh wow, that is dumb. Seems to work now. Thanks!

I'm having the same error when requriing endercore and enderio in a dev env, how exactly did you fix it? I've tried adding it to build.gradle like so
```
deobfCompile 'curse.maven...'
```

**Comment by HenryLoenwind** [comment]
You open the endercore jar file and extract the embedded core-core jar file that is in there in the meta-inf folder (I think it's there) into your mods folder.
