### ISSUE TITLE
EnderCore crash code -1

### ISSUE THREAD

**Issue by SpigoNico02** [SleepyTrousers/EnderCore#134]
on Cursed forge i create a modpuck, end i tried  for play  but when starting it after loading the mods it closes with the error -1 now and this is given to me as a report of the error, Thanks to anyone who can help me
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 5/31/23 12:05 PM
Description: Initializing game

java.lang.NoSuchMethodError: appeng.api.storage.ICellRegistry.getCellInventory(Lnet/minecraft/item/ItemStack;Lappeng/api/storage/ISaveProvider;Lappeng/api/storage/IStorageChannel;)Lappeng/api/storage/IMEInventoryHandler;
	at com.thiakil.appliedfluidics.item.ItemFluidicStorageCell.func_77624_a(ItemFluidicStorageCell.java:150)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$1032/1136954659.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$1055/1757253041.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.thiakil.appliedfluidics.item.ItemFluidicStorageCell.func_77624_a(ItemFluidicStorageCell.java:150)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$1032/1136954659.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$1055/1757253041.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 301434832 bytes (287 MB) / 2021654528 bytes (1928 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 41 mods loaded, 41 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version           | Source                                             | Signature                                |
	|:----- |:--------------------------------- |:----------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2            | minecraft.jar                                      | None                                     |
	| LCH   | mcp                               | 9.42              | minecraft.jar                                      | None                                     |
	| LCH   | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                             | 14.23.5.2859      | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | appleskin                         | 1.0.14            | AppleSkin-mc1.12-1.0.14.jar                        | None                                     |
	| LCH   | appliedenergistics2               | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | endercore                         | 1.12.2-0.5.76     | EnderCore-1.12.2-0.5.76.jar                        | None                                     |
	| LCH   | enderio                           | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderiointegrationtic             | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | mantle                            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| LCH   | tconstruct                        | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| LCH   | appliedfluidics                   | 1.12.2-2.0.3      | AppliedFluidics-1.12.2-2.0.3.jar                   | None                                     |
	| LCH   | codechickenlib                    | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | avaritia                          | 3.3.0             | Avaritia-1.12.2-3.3.0.37-universal.jar             | None                                     |
	| LCH   | redstoneflux                      | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCH   | brandonscore                      | 2.4.20            | BrandonsCore-1.12.2-2.4.20.162-universal.jar       | None                                     |
	| LCH   | carryon                           | 1.12.3            | carryon-1.12.2-1.12.7.23.jar                       | None                                     |
	| LCH   | crafttweaker                      | 4.1.20            | CraftTweaker2-1.12-4.1.20.688.jar                  | None                                     |
	| LCH   | ctgui                             | 1.0.0             | CraftTweaker2-1.12-4.1.20.688.jar                  | None                                     |
	| LCH   | crafttweakerjei                   | 2.0.3             | CraftTweaker2-1.12-4.1.20.688.jar                  | None                                     |
	| LCH   | cucumber                          | 1.1.3             | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
	| LCH   | cyclicmagic                       | 1.20.12           | Cyclic-1.12.2-1.20.14.jar                          | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
	| LCH   | draconicevolution                 | 2.3.28            | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar | None                                     |
	| LCH   | enderiobase                       | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderioconduits                   | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderioconduitsappliedenergistics | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderioconduitsopencomputers      | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderioconduitsrefinedstorage     | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderiointegrationforestry        | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderiointegrationticlate         | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderioinvpanel                   | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderiomachines                   | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | enderiopowertools                 | 5.3.70            | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| LCH   | ic2                               | 2.8.222-ex112     | industrialcraft-2-2.8.222-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | jaopcasingularities               | 1.12.2-3.0.0.0    | JAOPCASingularities-1.12.2-3.0.0.0.jar             | None                                     |
	| LCH   | jaopca                            | 1.12.2-2.3.8.13   | JAOPCA-1.12.2-2.3.8.13.jar                         | None                                     |
	| LCH   | journeymap                        | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LCH   | mysticalagriculture               | 1.7.5             | MysticalAgriculture-1.12.2-1.7.5.jar               | None                                     |
	| LCH   | naturescompass                    | 1.8.5             | NaturesCompass-1.12.2-1.8.5.jar                    | None                                     |
	| LCH   | projecte                          | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                        | None                                     |
	| LCH   | wrapup                            | 1.12-1.1.3        | WrapUp-1.12-1.1.3.jar                              | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 23.4.3.230420' Renderer: 'AMD Radeon RX 6650 XT'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Ender IO: No known problems detected.
	Authlib is : /C:/Users/Desktop/curseforge/minecraft/Install/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Launched Version: forge-14.23.5.2859
	LWJGL: 2.9.4
	OpenGL: AMD Radeon RX 6650 XT GL version 4.6.0 Compatibility Profile Context 23.4.3.230420, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 5600G with Radeon Graphics

**Comment by michaelortnersanube** [comment]
I think you use https://www.curseforge.com/minecraft/mc-mods/applied-fluidics - try to remove it and try it again

**Comment by tyler489** [comment]
Seems to be inside applied fluidity, try reporting it to them.
