### ISSUE TITLE
Can't load MC on Forge 1968 with EnderCore

### ISSUE THREAD

**Issue by raoulvdberge** [SleepyTrousers/EnderCore#48]
EnderCore-1.9.4-0.4.0.26
```
java.lang.NoSuchMethodError: net.minecraft.util.text.translation.I18n.func_74837_a(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
	at com.enderio.core.common.Lang.localizeExact(Lang.java:80) ~[EnderCore-1.9.4-0.4.0.26-alpha.jar:?]
	at com.enderio.core.common.Lang.localize(Lang.java:52) ~[EnderCore-1.9.4-0.4.0.26-alpha.jar:?]
	at com.enderio.core.common.config.AbstractConfigHandler.addCommentDetails(AbstractConfigHandler.java:545) ~[EnderCore-1.9.4-0.4.0.26-alpha.jar:?]
	at com.enderio.core.common.config.ConfigProcessor.getConfigValue(ConfigProcessor.java:294) ~[EnderCore-1.9.4-0.4.0.26-alpha.jar:?]
	at com.enderio.core.common.config.ConfigHandler$1.getConfigValue(ConfigHandler.java:146) ~[EnderCore-1.9.4-0.4.0.26-alpha.jar:?]
	at com.enderio.core.common.config.ConfigProcessor.processField(ConfigProcessor.java:232) ~[EnderCore-1.9.4-0.4.0.26-alpha.jar:?]
	at com.enderio.core.common.config.ConfigProcessor.process(ConfigProcessor.java:207) ~[EnderCore-1.9.4-0.4.0.26-alpha.jar:?]
	at com.enderio.core.common.config.ConfigHandler.init(ConfigHandler.java:161) ~[EnderCore-1.9.4-0.4.0.26-alpha.jar:?]
	at com.enderio.core.common.config.AbstractConfigHandler.initialize(AbstractConfigHandler.java:89) ~[EnderCore-1.9.4-0.4.0.26-alpha.jar:?]
	at com.enderio.core.EnderCore.preInit(EnderCore.java:102) ~[EnderCore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:568) ~[forgeSrc-1.9.4-12.17.0.1968-PROJECT(refinedstorage).jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228) ~[forgeSrc-1.9.4-12.17.0.1968-PROJECT(refinedstorage).jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206) ~[forgeSrc-1.9.4-12.17.0.1968-PROJECT(refinedstorage).jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:586) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:475) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:384) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_71]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_71]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:?]
```

**Comment by CrazyPants** [comment]
That is a dud build of forge. Please update.

**Comment by fritte69** [comment]
This still happens with Forge-1.10.2-12.18.0.2010.
The reference is in the localizeExact() method in com.enderio.core.common.Lang.class file.

**Comment by raoulvdberge** [comment]
Still happens on Forge 2014. If it is of any help, this error occurs when loading EnderCore from a dev environment.

**Comment by CrazyPants** [comment]
In eclipse? If so try removing the -DFORCE... VM arg

**Comment by raoulvdberge** [comment]
In Intellij
