### ISSUE TITLE
Closing the Inventory Panel interface causes crash with alpha 12.

### ISSUE THREAD

**Issue by rrongol** [SleepyTrousers/EnderCore#7]
Since upgrading from EnderCore-1.7.10-0.0.1.11_alpha to EnderCore-1.7.10-0.0.1.12_alpha I noticed the following error:

When closing the Inventory Panel interface, Minecraft displays the following message, then exits to the main menu.

"Shutting down internal server..."
and then
"Connection lost"  "A fatal error has occurred, this connection is terminated"

This happens every time I close the Inventory Panel interface.  I tried several other machines and nothing else caused this error.  If I downgrade back to EnderCore-1.7.10-0.0.1.11_alpha, then the Panel works fine.

**Comment by tterrag1098** [comment]
I need the log to be able to do anything.

**Comment by rrongol** [comment]
There is nothing in the crash-reports folder.  I've included the contents of the logs/latest.log file below.  Would anything else help?

[19:36:42] [main/INFO]: Setting user: orlorn
[19:36:43] [Client thread/INFO]: LWJGL Version: 2.9.1
[19:36:52] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:The Deconstruction Mod, FMLFileResourcePack:Baubles, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:ChickenChunks, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Doomlike Dungeons, FMLFileResourcePack:Enchanting Plus, FMLFileResourcePack:EnderCore, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderStorage, FMLFileResourcePack:EnderTech, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:JABBA, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:Nether Ores, FMLFileResourcePack:Reconstructor, FMLFileResourcePack:Redstone Arsenal, FMLFileResourcePack:RFDrills, FMLFileResourcePack:Simply Jetpacks, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:Waila, Sphax Base x064, Sphax Mods x064
[19:36:59] [Sound Library Loader/INFO]: Sound engine started
[19:37:00] [Client thread/INFO]: Created: 16x16 textures/blocks-atlas
[19:37:00] [Client thread/INFO]: Created: 16x16 textures/items-atlas
[19:37:07] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Not Enough Items, FMLFileResourcePack:The Deconstruction Mod, FMLFileResourcePack:Baubles, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:ChickenChunks, FMLFileResourcePack:CoFH Core, FMLFileResourcePack:Doomlike Dungeons, FMLFileResourcePack:Enchanting Plus, FMLFileResourcePack:EnderCore, FMLFileResourcePack:Ender IO, FMLFileResourcePack:EnderStorage, FMLFileResourcePack:EnderTech, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:JABBA, FMLFileResourcePack:JourneyMap, FMLFileResourcePack:Nether Ores, FMLFileResourcePack:Reconstructor, FMLFileResourcePack:Redstone Arsenal, FMLFileResourcePack:RFDrills, FMLFileResourcePack:Simply Jetpacks, FMLFileResourcePack:Thermal Dynamics, FMLFileResourcePack:Thermal Expansion, FMLFileResourcePack:Thermal Foundation, FMLFileResourcePack:Waila, Sphax Base x064, Sphax Mods x064
[19:37:28] [Client thread/INFO]: Created: 4096x2048 textures/blocks-atlas
[19:37:29] [Client thread/INFO]: Created: 2048x2048 textures/items-atlas
[19:37:30] [Sound Library Loader/INFO]: Sound engine started
[19:37:33] [Client thread/ERROR]: ########## GL ERROR ##########
[19:37:33] [Client thread/ERROR]: @ Post startup
[19:37:33] [Client thread/ERROR]: 1286: Invalid framebuffer operation
[19:37:39] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[19:37:39] [Server thread/INFO]: Generating keypair
[19:37:39] [Server thread/INFO]: Preparing start region for level 0
[19:37:40] [Server thread/INFO]: Preparing spawn area: 50%
[19:37:43] [Server thread/INFO]: orlorn[local:E:c8e624d5] logged in with entity id 1076 at (182.16534788320465, 75.0, 290.8341529890567)
[19:37:43] [Server thread/INFO]: orlorn joined the game
[19:37:44] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2094ms behind, skipping 41 tick(s)
[19:37:54] [Client thread/INFO]: [CHAT] §eJourneyMap:§f Press [§bM§f]
[19:37:54] [Server thread/INFO]: Saving and pausing game...
[19:37:54] [Server thread/INFO]: Saving chunks for level 'Survival World'/Overworld
[19:37:54] [Server thread/INFO]: Saving chunks for level 'Survival World'/Nether
[19:37:54] [Server thread/INFO]: Saving chunks for level 'Survival World'/The End
[19:37:54] [Server thread/INFO]: Saving chunks for level 'Survival World'/Underdark
[19:37:54] [Server thread/INFO]: Saving chunks for level 'Survival World'/The Last Millenium
[19:38:08] [Server thread/INFO]: Saving and pausing game...
[19:38:08] [Server thread/INFO]: Saving chunks for level 'Survival World'/Overworld
[19:38:08] [Server thread/INFO]: Saving chunks for level 'Survival World'/Nether
[19:38:08] [Server thread/INFO]: Saving chunks for level 'Survival World'/The End
[19:38:08] [Server thread/INFO]: Saving chunks for level 'Survival World'/Underdark
[19:38:08] [Server thread/INFO]: Saving chunks for level 'Survival World'/The Last Millenium
[19:38:21] [Server thread/INFO]: orlorn lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[19:38:21] [Server thread/INFO]: orlorn left the game
[19:38:21] [Server thread/INFO]: Stopping singleplayer server as player logged out
[19:38:21] [Server thread/INFO]: Stopping server
[19:38:21] [Server thread/INFO]: Saving players
[19:38:21] [Server thread/INFO]: Saving worlds
[19:38:21] [Server thread/INFO]: Saving chunks for level 'Survival World'/Overworld
[19:38:21] [Server thread/INFO]: Saving chunks for level 'Survival World'/Nether
[19:38:21] [Server thread/INFO]: Saving chunks for level 'Survival World'/The End
[19:38:21] [Server thread/INFO]: Saving chunks for level 'Survival World'/Underdark
[19:38:21] [Server thread/INFO]: Saving chunks for level 'Survival World'/The Last Millenium
[19:38:26] [Client thread/INFO]: Stopping!

**Comment by rrongol** [comment]
Ah, browsing through the logs/fml-client-latest.log file I see the following.  Does this help?

[19:38:21] [Client thread/ERROR] [FML/]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.IndexOutOfBoundsException: readerIndex: 49 (expected: 0 <= readerIndex <= writerIndex(17))
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:236) [SimpleNetworkWrapper.class:?]
	at crazypants.enderio.machine.invpanel.TileInventoryPanel.setGuiParameter(TileInventoryPanel.java:241) [TileInventoryPanel.class:?]
	at crazypants.enderio.machine.invpanel.GuiInventoryPanel.func_146281_b(GuiInventoryPanel.java:226) [GuiInventoryPanel.class:?]
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:791) [bao.class:?]

**Comment by MatthiasMann** [comment]
This has been fixed in build 400 of EnderIO now available on the CI server.
