### ISSUE TITLE
EnderCore-1.12.2-0.5.38.jar causes crash with EnderIO-1.12.2-5.0.31.jar 

### ISSUE THREAD

**Issue by Guinaro** [SleepyTrousers/EnderCore#93]
Previous version of EnderCore (-0.5.37) works fine.
Error Message:
```Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ender IO (enderio)
Caused by: java.lang.NoSuchMethodError: com.enderio.core.common.util.NullHelper.notnull(Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
	at crazypants.enderio.base.config.factory.EnumValue.<init>(EnumValue.java:17)
	at crazypants.enderio.base.config.factory.SlaveFactory.make(SlaveFactory.java:90)
	at crazypants.enderio.base.config.config.EnchantmentConfig.<clinit>(EnchantmentConfig.java:23)
	at crazypants.enderio.base.config.config.BaseConfig.load(BaseConfig.java:12)
	at crazypants.enderio.base.config.Config.processConfig(Config.java:708)
	at crazypants.enderio.base.config.Config.syncConfig(Config.java:263)
	at crazypants.enderio.base.config.Config.init(Config.java:255)
	at crazypants.enderio.base.EnderIO.preInit(EnderIO.java:121)```

**Comment by HenryLoenwind** [comment]
Don't mix versions that don't belong together. ec 37 is for eio 32

**Comment by Guinaro** [comment]
I'm sorry to say: but nowhere does it state on the Curseforge pages which EnderCore belongs to which enderio. Furthermore EnderIO 32 is currently not available on curseforge.
I simply chose in the Twitch app to use alpha builds. And that was the combination it got when starting up Minecraft.
I downgraded the EC38 to EC37 and stayed with EIO31 and minecraft started up. So I assume you mean EC38 is for EIO 32 (as of yet not available)
In all honesty this could all very well be a mixup/delay in the Curseforge pages not yet showing the EIO.32, however maybe when uploading endercore versions a mentions in the changes that it requires a certain EIO version would clear up a lot. And maybe vice versa when uploading EnderIO a mention of the minimum required EC version

Sinceerly,
Guinaro

**Comment by kreezxil** [comment]
possibly the same issue here.
I use Twitch app to build and maintain my modpacks such as the very popular World of Dragons.


Issue:  1.12.2-0.5.38 crashes dedicated server Forge 1.12.2 build 2750

Notes:
     No Such Method Error

crash report:
https://gist.github.com/a5b54003f9671092ae21a8639ea49980

fml server latest:
https://gist.github.com/83375a16c961c1ba93922628e54f6d82

I'll put endercore on the previous version to resolve this.
